# Generated by Django 3.2.4 on 2021-09-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='images',
            field=models.ImageField(null=True, upload_to='images/games_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='images/product_images/'),
        ),
    ]
