# Generated by Django 3.2.4 on 2021-09-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210903_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='images',
            new_name='image',
        ),
    ]
